# HTTP status codes
OK = 200
BAD_REQUEST = 400
NOT_FOUND = 404

# Consumption parameters
MIN_WIND_SPEED = 5
MAX_WIND_SPEED = 28
MIN_AIR_DENSITY = 1.20
MAX_AIR_DENSITY = 1.28
DAY_TEMPERATURE = 18.0
NIGHT_TEMPERATURE = 9.0

# Main API endpoint
API_ROOT = "energy"

# Battery parameters
BATTERY_ALERT_THRESHOLD = 200
